version: '3.8' # version 20.10.5

services: 
    cache:
        image: redis
        volumes:
            - ./data:/data
        ports:
            - '6379:6379'
        command: ['--requirepass "secret"']